### ISSUE TITLE
[easy to fix list] If you are interested in a task, please open this issue link and leave a message in its comment area, and I will assign the task to you

### ISSUE THREAD

**Issue by xingchun-chen** [xingchun-chen/xingchun-chen.github.io#61]
The following list is the latest newbie tasks (keep up to date). If you are participating in an open source project for the first time, it is recommended to choose one of the following tasks to practice. The first task is used to familiarize yourself with the submission process and feel the friendliness of the community. If you are interested in a task, please leave a message, and then I will assign the task to you. By the way, please submit a PR in 2 weeks 

---
下面是最新的新手任务列表(一直保持更新, 新手贡献者只看我这一条信息就够了)，如果您是第一次参与开源贡献，建议从以下任务列表中选择一个练手，第一个任务用于熟悉提交流程和感受社区友好度。如果您对某个任务感兴趣，请打开这个 issue 链接在其评论区留言，然后我会将该任务分给您，认领后请于 2 周内提交一个 PR,  2 周后没提交 PR 的话，这个新手任务也可以由新伙伴来认领哈! 

TODO list

- [ ] [Improvement][job instance]start-time and end-time good first issue volunteer wanted #5621 

- [ ] [Improvement][project management] Modify the title easy to fix good first issue user experience #5622 

- [ ] [Doc] move the Doc of Ambari Integration to official website repository #5608

- [ ] [code][uint test] Improve code test coverage( This is a big feature,  You can create sub-issues for specific sub-issues)

- [ ] [Improvement][Api] Adding transaction when update process definition #5546

- [ ] [Improvement][SQL]SQL optimization( This is a big feature, You can create sub-issues for specific sub-issues) #5061 
 

submit code：https://dolphinscheduler.apache.org/zh-cn/community/development/submit-code.html
pr and code style notice：https://dolphinscheduler.apache.org/zh-cn/community/development/pull-request.html
